
@baseUrl = http://localhost:3000/api

# @name getAllProducts
GET {{baseUrl}}/accounts

###
# @name addNewProducts 

POST {{baseUrl}}/products
Content-Type: application/json

{
    "name" : "Nguyen laptop",
    "categoryId" : 1,
    "price" : 175000
}

###
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "username" : "Nguyen laptop",
    "password" : "123455"
}


###

# @name updateProducts
PATCH  {{baseUrl}}/products/4
Content-Type: application/json

{
    "name" : "Tran Khanh Duy"
}

###

# @name deleteProducts
DELETE {{baseUrl}}/products/3

